# Generated by Django 5.2.4 on 2025-08-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='tipo',
            new_name='type',
        ),
    ]
